---
title: "16S rRNA pipeline using DADA2"
author: 'Instructors: Imane Allali'
---


<br/><br/>

## <span style="color:green">General Information</span>
The material of taught in this module was developed by [Benjamin Callahan](https://github.com/benjjneb).

**Who** : The course is aimed at Master, PhD students, and other researchers.

**When** : From 28 September to 25 November 2021.

**Requirements**: Participants must have access to R or RStudio via their own computer or cluster.


**Contact** : Please email allali.imane@gmail.com for more information.
<br/><br/>

#### Prerequisities
You should have your access to R and RStudio via your own compute or cluster.
<br/><br/>

#### Outcomes
1. Understand each step of 16S rRNA analysis pipeline using DADA2
2. Run 16S rRNA analysis pipeline from raw reads
3. Know how to edit files and use command line
4. Choose the best approach and tools to analyze your data
<br/><br/>

#### When you get lost or something is unclear
1. Please find someone next to you that looks like they know what they are doing.
2. Ask the teacher assistant.
3. Let me know.
<br/><br/>

